// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("OpenCLManagedWrapper")]
[assembly: AssemblyProductAttribute("FSCL.Compiler")]
[assembly: AssemblyDescriptionAttribute("F# to OpenCL compiler")]
[assembly: AssemblyVersionAttribute("2.0")]
[assembly: AssemblyFileVersionAttribute("2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0";
    }
}
